### ISSUE TITLE
LUA & Python support

### ISSUE THREAD

**Issue by vk496** [majn/tgl#21]
Hi, as I mentioned in #20, I'm trying to port the telegram-cli to Big Endian.

I saw somewhere that this library deleted lua & python support. That means that will be impossible to use lua & python scripts (bot mode)? Or this change of library not affect to the client?

Salu2

**Comment by BenWiederhake** [comment]
To the best of my knowledge, tgl *never had* lua and python support.  Maybe you mixed up tl-cli (full command-line program, uses tgl) and tgl (a library, needs to be linked before use)?

Good luck with trying to port it.  See the tope two commits of this for a start of porting tl-parser (a tool originally separate of tgl, but only useful for building tgl).  Since `tl-parser` and `generate` "only" generate source code, it is viable to skip it and work on tgl directly.
In my eyes, porting it to be endian-correct is neigh-impossible because tgl uses the idiom `write(fd, &mystruct, sizeof(mystruct))` everywhere.  There may be more issues.
